//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_category_master
    {
        public int food_cat_id { get; set; }
        public string food_cat_name { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public bool is_active { get; set; }
        public bool is_delete { get; set; }
    }
}
