//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chef_collect_order_master
    {
        public int chef_collect_order_id { get; set; }
        public int Order_assign_id { get; set; }
        public bool is_start { get; set; }
        public bool is_done { get; set; }
        public Nullable<bool> is_active { get; set; }
        public bool is_delete { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
    
        public virtual order_assign_master order_assign_master { get; set; }
    }
}
