//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_category_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food_category_master()
        {
            this.food_item_master = new HashSet<food_item_master>();
            this.speciality_master = new HashSet<speciality_master>();
        }
    
        public int food_cat_id { get; set; }
        public string food_cat_name { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public bool is_active { get; set; }
        public bool is_delete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_item_master> food_item_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<speciality_master> speciality_master { get; set; }
    }
}
