//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class food_item_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food_item_master()
        {
            this.order_item = new HashSet<order_item>();
            this.order_master = new HashSet<order_master>();
            this.rating_master = new HashSet<rating_master>();
        }
    
        public int food_item_id { get; set; }
        public int food_cat__id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public double amount { get; set; }
        public int quantity { get; set; }
        public int discount { get; set; }
        [DisplayName("Upolad Image")]
        public string image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public bool is_active { get; set; }
        public bool is_delete { get; set; }
    
        public virtual food_category_master food_category_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_master> order_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rating_master> rating_master { get; set; }
    }
}
