//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class canteen_manege_systemEntities13 : DbContext
    {
        public canteen_manege_systemEntities13()
            : base("name=canteen_manege_systemEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chef_collect_order_master> chef_collect_order_master { get; set; }
        public virtual DbSet<feedback_master> feedback_master { get; set; }
        public virtual DbSet<food_category_master> food_category_master { get; set; }
        public virtual DbSet<food_item_master> food_item_master { get; set; }
        public virtual DbSet<order_assign_master> order_assign_master { get; set; }
        public virtual DbSet<order_item> order_item { get; set; }
        public virtual DbSet<order_master> order_master { get; set; }
        public virtual DbSet<payment_master> payment_master { get; set; }
        public virtual DbSet<rating_master> rating_master { get; set; }
        public virtual DbSet<speciality_master> speciality_master { get; set; }
        public virtual DbSet<user_master> user_master { get; set; }
    }
}
