//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_assign_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_assign_master()
        {
            this.chef_collect_order_master = new HashSet<chef_collect_order_master>();
        }
    
        public int Order_assign_id { get; set; }
        public Nullable<int> order_master_id { get; set; }
        public Nullable<int> speciality_id { get; set; }
        public Nullable<int> cheif_type { get; set; }
        public string reject_msg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chef_collect_order_master> chef_collect_order_master { get; set; }
        public virtual order_master order_master { get; set; }
        public virtual speciality_master speciality_master { get; set; }
    }
}
