//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_master()
        {
            this.order_assign_master = new HashSet<order_assign_master>();
            this.order_item = new HashSet<order_item>();
            this.payment_master = new HashSet<payment_master>();
        }
    
        public int order_master_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> food_item_id { get; set; }
        public Nullable<double> total_price { get; set; }
        public Nullable<int> quantity { get; set; }
        public System.TimeSpan order_deliverytime { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.TimeSpan> create_time { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual food_item_master food_item_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_assign_master> order_assign_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual user_master user_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_master> payment_master { get; set; }
    }
}
