//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_master
    {
        public int rating_id { get; set; }
        public int food_item_id { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> create_datetime { get; set; }
        public Nullable<System.DateTime> update_datetime { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public int user_id { get; set; }
    
        public virtual food_item_master food_item_master { get; set; }
        public virtual user_master user_master { get; set; }
        public virtual rating_master rating_master1 { get; set; }
        public virtual rating_master rating_master2 { get; set; }
    }
}
