//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace canteen_management_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class speciality_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public speciality_master()
        {
            this.order_assign_master = new HashSet<order_assign_master>();
        }
    
        public int speciality_id { get; set; }
        public int user_id { get; set; }
        public int food_cat_id { get; set; }
        public string qualification { get; set; }
        public int experience { get; set; }
        public bool is_approed { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_delete { get; set; }
    
        public virtual food_category_master food_category_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_assign_master> order_assign_master { get; set; }
        public virtual user_master user_master { get; set; }
    }
}
